### ISSUE TITLE
Diamond package available

### ISSUE THREAD

**Issue by retr0h** [BrightcoveOS/Diamond#187]
I would like to request diamond be added upstream to debian/ubuntu sources.  I am looking to use diamond, but as it stands there it requires either building the package and hosting it in an apt repo we maintain, or installing via git.

These obviously are not ideal, and IMO should be added upstream to linux package maintainers.  Until then it would be helpful if you guy had packages at your own ppa.  I can add pull requests to the existing chef cookbooks to add the ppa so a package installation is possible, until the package is upstreamed into the appropriate Linux distros.

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
