### ISSUE TITLE
Handlers keeping a publish counter

### ISSUE THREAD

**Issue by rtoma** [BrightcoveOS/Diamond#262]
What about handlers keeping and increasing a counter for every metric published, which we periodically flush to the registered Handlers?

With this enhancement one can easilly see if all collectors are working and which Diamond instance is very busy.

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
