### ISSUE TITLE
Problem with Custom Collectors diamond

### ISSUE THREAD

**Issue by CecsKul** [BrightcoveOS/Diamond#305]
Hi all !
I wrote one collector under the guidance https://github.com/BrightcoveOS/Diamond/wiki/CustomCollectors . 
I  pushed succeed metric to server graphite after running the command :
$/etc/init.d/diamond stop
$diamond -f -r path/to/ExampleCollector.py -c conf/diamond.conf.example
But diamond only pushed metric after each this command . So metrics was discontinuous when plotted on charts . 
when I run the diamond back, the data is not received . 
Help me plz . Thanks a lot .

**Comment by zhulinhong** [comment]
You need to add the "ExampleCollector" to diamond.conf.example

[[ExampleCollector]]
enabled = True
