### ISSUE TITLE
build a celery collector

### ISSUE THREAD

**Issue by Henner** [BrightcoveOS/Diamond#373]
http://docs.celeryproject.org/en/latest/userguide/monitoring.html
or
http://docs.celeryproject.org/en/latest/userguide/signals.html

with: running / error / success for tasks splitted over queues

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
