### ISSUE TITLE
Allow collectors to override the set metric path

### ISSUE THREAD

**Issue by mjulian** [BrightcoveOS/Diamond#405]
In some cases, such as how I'm using Diamond, overriding the predetermined metric path would be very useful.

For example, I'm using Diamond to poll routers and switches, and it would make more sense that these would show up as their own metric path, and not as a path underneath my polling server.

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
