### ISSUE TITLE
rpm dependency handling

### ISSUE THREAD

**Issue by KlavsKlavsen** [BrightcoveOS/Diamond#452]
Just had an issue.. this time with the rabbitmq collector.

It requires pyrabbitapi, which requires python-httplib2 and Numbers (part of base).

The spec built with your rpm make script, does not specify depencies unfortunately.
also - if you did-  those NOT using rabbitmq collector, might not want the dependencies for it :)

The normal solution, is to create several packages in your .spec - and specify dependencies for each - so one gets several rpms - f.ex. diamond-collector-rabbitmq - which would then have:
require: python-httplib2 python-rabbitmq 

based on the naming from pypi site.

Best would be if rpm specs supported the actual module names, like it does for perl: python(rabbitmqapi) - that way, any package name could provide it, or it could be installed manually.

But I don't think it does.

I'll gladly assist with whatever I can.

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
