### ISSUE TITLE
postgre collector: global metrics shouldn't be listed under a given db

### ISSUE THREAD

**Issue by sanga** [BrightcoveOS/Diamond#476]
for example the locks metrics are marked as multi_db=False and are global so the at least in the case of locks the graphite metric name shouldn't be under a single db but rather one step up towards the root of the metric tree (more easily explained by example I guess):

current:
.postgres.db1.locks.
more reasonable (in my opinion):
.postgres.locks.

I left this as generic as there might be other cases of this problem for other metrics (it'd be worth glancing through the code)

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
