### ISSUE TITLE
can't the mysql collector auto-detect master or slave?

### ISSUE THREAD

**Issue by Dieterbe** [BrightcoveOS/Diamond#515]
if you have a bunch of mysql servers, and sometimes they transition from master to slave or vice versa (or both a master and a slave), it would be nice if the mysql collector could automatically detect whether the instance is a master and/or a slave, and submit the appropriate metrics accordingly.

otherwise it can be cumbersome to make sure the diamond configs are in sync.

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
