### ISSUE TITLE
Two configs for one collector

### ISSUE THREAD

**Issue by bestxolodec** [BrightcoveOS/Diamond#545]
Is there any way to have two configs for one collector file? 
I wrote my own collector and need to run it with different options on one machine. 
I can't find any option in config file that  allows to run arbitrary named collector.
Is it mandatory to have collector's class name  coincide with name of collector config?

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
