### ISSUE TITLE
diskspace collector creates metrics w/ spaces

### ISSUE THREAD

**Issue by davidbirdsong** [BrightcoveOS/Diamond#549]
When collecting diskspace metrics on OSX 10.8, spaces are included in the outgoing graphite-carbon metric key:

```
.diskspace._Volumes_Macintosh HD2.inodes_avail 243944553 1394132682
```

I'm happy to send a PR, but wanted to get your preference on where the fix belongs. I could patch the collector, but since this is more of a graphite issue, perhaps the fix belongs in the [graphite.py](https://github.com/BrightcoveOS/Diamond/blob/master/src/diamond/handler/graphite.py#L101)?

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!

**Comment by Dieterbe** [comment]
thanks for everything @kormoc :)
