### ISSUE TITLE
Diamond self monitoring

### ISSUE THREAD

**Issue by direvius** [BrightcoveOS/Diamond#558]
We have a lot of Diamond copies installed on different machines and sometimes we have gaps on ProcessResources' graphs. So I need some metrics about Diamond itself.

Now I'm using the ProcessResources collector to gather information about resource usage, but I also need GraphiteHandler's backlog current size, sent metrics count, trimmed metrics count, collectors timings. Are there any collectors that provide such kind of information?

If there aren't, which is the preffered way to implement that? One would do that by collecting selfmon metrics directly inside of the GraphiteHandler class or make an external collector.

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
