### ISSUE TITLE
Upgrading Elasticsearch plugin to the 1.X version

### ISSUE THREAD

**Issue by athoune** [BrightcoveOS/Diamond#569]
I started a branch with an upgradred version of the Elasticsearch plugin.

https://github.com/bearstech/Diamond/compare/master...elasticsearch_1_0

I drop compabilitiy with the previous version, and tricks to handle pre-stable version of Elasticsearch. The path for key is mapped to Elasticsearch path, metrics from differents node is now possible.

This version is used in productin, but lots of dead code is left.

Any suggestion (I will cleanup dead code and add tests), for a nice pull request?

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
