### ISSUE TITLE
Handler slowness could lead to incorrect derivative when using sequential method

### ISSUE THREAD

**Issue by nikicat** [BrightcoveOS/Diamond#616]
derivative is calculated using predefined interval (taken from config), but actual check interval could be much larger if some collector or handler works slow. With sequential method enabled by default for cpu and network collectors, this could lead to very distorted points.
Possible workarounds are
- use threaded task method, or
- make cpu and network collectors to return absolute data and calculate derivative on server side, e.g. graphite (IMHO, better and more robust solution)

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
