### ISSUE TITLE
StatsD handler needs to support integers for gauges instead of floating point. 

### ISSUE THREAD

**Issue by zahlenofzahlen** [BrightcoveOS/Diamond#620]
Suggest wrapping metric.value with int(metric.value) for the statsd handler. It won't work with hekaD because it violates the spec. HekaD treats these as null values instead of throwing an exception. 

https://github.com/b/statsd_spec 

The protocol allows for both integer and floating point values. Most implementations store values internally as a IEEE 754 double precision float, but many implementations and graphing systems only support integer values. For compatibility all values should be integers in the range (-2^53^, 2^53^).

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
