### ISSUE TITLE
Hadoop collector for Hadoop Metrics2

### ISSUE THREAD

**Issue by smallredbean** [BrightcoveOS/Diamond#645]
Hadoop Metrics2 outputs timestamps in milliseconds*. Hadoop collectors should convert them into seconds before publishing it. However, I have no knowledge about Hadoop Metric; unable to tell if this would be backward compatible.

*I'm using AWS EMR service with AMI 2.4.2 & Hadoop 1.0.3

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
