### ISSUE TITLE
Question: (wiki page?) how-to write tests for collectors?

### ISSUE THREAD

**Issue by zstyblik** [BrightcoveOS/Diamond#649]
Hello,

as subject suggests, I wonder whether somebody could give me quick how-to write tests for Diamond's collectors and which packages to install(I'm using Debian)? What's the common/accepted way to write tests and how to get started?

I just need to get hooked up. I'm sure I can manage by myself after that ;) May be, I'll write a wiki page about it as a result.

Thanks in advance!

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
