### ISSUE TITLE
pg collector could yield inconsistent results

### ISSUE THREAD

**Issue by zstyblik** [BrightcoveOS/Diamond#683]
Hello,

this have occurred to me some time ago, but I didn't have time to write it down. This is based on my understanding how PgSQL collector works, which, of course, can be wrong.

Let's have a model situation. We have a PgSQL database with tables:
- b
- c
- d

The fist problem I saw was in `_get_db_names()`:

``` python
    def _get_db_names(self):
        # [...]
        conn = self._connect(self.config['dbname'])
        cursor = conn.cursor(cursor_factory=psycopg2.extras.DictCursor)
        cursor.execute(query)
        datnames = [d['datname'] for d in cursor.fetchall()]
        # [...]

        return datnames
```

Sorted list should be returned, right? Because there are queries that aren't executed against all DBs, but are executed only against one DB. So what would happen if instead of `['b', 'c', 'd']`, we get `['d','c','b']`? Never mind this one.

Let's presume order of DB names never ever changes and it's always same. Will it be the same even if we add DB with name `a`? Now, we're no longer collecting one-off queries against DB `b`, but we're collecting against DB `a`. And this seems like something we don't want.

I guess the only solution is to define(via configuration attribute/option) one database for one off queries.

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
