### ISSUE TITLE
Testcase for testrabbitmq.TestRabbitMQCollector fails

### ISSUE THREAD

**Issue by rtoma** [BrightcoveOS/Diamond#704]
Someone please have a look at testrabbitmq.TestRabbitMQCollector - it fails and I cannot find it why.

My gut says it fails because of a major change in the rabbitmq client library, causing an incorrect/incomplete mocking.

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
