### ISSUE TITLE
Some collectors occasionally post floats in scientific notation

### ISSUE THREAD

**Issue by Synforge** [BrightcoveOS/Diamond#723]
I've got a bit of an issue with some collectors where they occasionally push their metric in scientific notation. For example with the disk usage collector:

`[2014-09-02 12:11:52,067] [Thread-1] host.vda2.concurrent_io: 9.97143369909e-05`
`[2014-09-02 12:11:52,076] [Thread-1] host.vda.concurrent_io: 9.97143369909e-05`

So far I've noticed this in the following collectors/metrics:
DiskUsage:
average_queue_length
concurrent_io

Cpu
iowait

I've also noticed a somewhat related issue with the mysql collector where it attempts to push the metric mysql_slave_running as a string of ON which is obviously invalid.

`2 Sep 12:20:12 - DEBUG: Bad line: ON,g in msg "host.mysql.slave_running:ON|g"`

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
