### ISSUE TITLE
redis missing instantaneous_ops_per_sec

### ISSUE THREAD

**Issue by davedash** [BrightcoveOS/Diamond#741]
It would be great if we could collect:

instantaneous_ops_per_sec

in Redis.

Looks like this fork does that:

https://github.com/damm/Diamond-1/blob/master/src/collectors/redisstat/redisstat.py

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
