### ISSUE TITLE
Haproxy/graphite pickle - Multiple timestamps per collection run

### ISSUE THREAD

**Issue by walkeran** [BrightcoveOS/Diamond#743]
This might be similar/related to #381, but I have some more info that might help.

The problem I'm running into is, every couple of minutes, I'll end up with a gap in my graphs. My graphite interval is 10 seconds, and my Diamond interval is 10 seconds. The problem crops up when Diamond starts collecting (and/or emitting) stats around the 9th second of a 10s interval. For instance, if my intervals in Graphite are 10:20:00, 10:20:10, 10:20:20, etc, and Diamond is sending the stats with timestamps 10:20:05, 10:20:15, 10:20:25, there's no problem... when it starts sending stats around 10:20:09, 10:20:19, etc, then I am experiencing the problem.

I did a handful of packet dumps, and found that it takes between 1.5 and 2 seconds for my Diamond agent to send all of my haproxy stats using the pickle protocol to my graphite servers. The underlying problem is that the timestamp included in packets sent to graphite seems to reflect when the stats were sent, as opposed to when the stats were collected.

For example, if Diamond collects haproxy stats at 10:20:09, and starts sending them, only 25% or so will have a timestamp of 10:20:09, and the rest will have a timestamp of 10:20:10 -- So, 25% of my stats will end up in the 10:20:00 "time period", and the other 75% will end up in 10:20:10. Then during the next run at 10:20:19, it will happen again, but maybe with a 50/50 split -- 50% of my stats end up in the 10:20:10 time period, and the other 50% will end up in 10:20:20.

I'm not much of a programmer, and am having a bit of a difficult time digging through the Diamond code to try to figure out why this is happening (problem with the haproxy collector? Graphitepickle handler?), or if it's by design, but if anyone else can shed some light on the situation, I'd be very grateful.

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
