### ISSUE TITLE
postgres plugin: locks query should be improved

### ISSUE THREAD

**Issue by sanga** [BrightcoveOS/Diamond#744]
At the moment the locks stats have no concept of what it is that is locked. So for example a row exclusive lock and a table exclusive lock will be binned to the same bin. Which you don't want as very likely a table exclusive lock is a much more serious problem than a row exclusive lock

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
