### ISSUE TITLE
RabbitMQCollector - legacy mode re-evaluated every time collection is run - logic only works first time

### ISSUE THREAD

**Issue by Ian2020** [BrightcoveOS/Diamond#753]
On the first collection run the legacy bool is correctly evaluated as true for configurations lacking the vhost block. However on subsequent runs the legacy bool switches back to false as vhosts is now present self.config. This means when diamond starts up we get the correct legacy behaviour once and then afterwards the metrics all move to the non-legacy location.

I'd be happy to have a crack at fixing this myself. I thought to move the 'legacy' calculation to a spot where it's done just once at start-up - would get_default_config be the right place?

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
