### ISSUE TITLE
dpkg --purge removes /lib/init/upstart-job

### ISSUE THREAD

**Issue by ghost** [BrightcoveOS/Diamond#758]
I've build a 3.5.8 .deb according to the instructions and installed it. I, perhaps stupidly, did a `dpkg --purge diamond` and found that instead of removing the /etc/init.d/diamond symlink /lib/init/upstart-job was removed instead.

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
