### ISSUE TITLE
add Slave_IO_Running and Slave_SQL_Running to MySQLCollector 

### ISSUE THREAD

**Issue by Gromph** [BrightcoveOS/Diamond#760]
I hacked them in by adding 'Slave_IO_Running' , 'Slave_SQL_Running' to _GAUGE_KEYS

The values of them are either Yes or No, so I converted to 1 or 0:
Add the following lines right above the line: metrics['slave'][key] = float(row_slave[key])
if row_slave[key] == "Yes": row_slave[key] = 1
if row_slave[key] == "No": row_slave[key] = 0

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
