### ISSUE TITLE
SNMPCollector

### ISSUE THREAD

**Issue by Issam6** [BrightcoveOS/Diamond#762]
Hi,

Does anyone know how to configure SNMPCollector.conf to use SNMP to collect data from a common PC (not a router or switch)? Is it possible? I noticed that there is no SNMPCollector.conf configuration example in the wiki. 

Thanks a lot.

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
