### ISSUE TITLE
byte-compiling error on rhel 5.5

### ISSUE THREAD

**Issue by kicker69101** [BrightcoveOS/Diamond#763]
When I'm trying to install on rhel 5.5, I get the following byte compile error:
<snip>
byte-compiling /usr/lib/python2.4/site-packages/diamond/metric.py to metric.pyc
byte-compiling /usr/lib/python2.4/site-packages/diamond/version.py to version.pyc
byte-compiling /usr/lib/python2.4/site-packages/diamond/**init**.py to **init**.pyc
byte-compiling /usr/lib/python2.4/site-packages/diamond/server.py to server.pyc
  File "/usr/lib/python2.4/site-packages/diamond/server.py", line 205
    except (KeyboardInterrupt, SystemExit) as err:
                                            ^
SyntaxError: invalid syntax
byte-compiling /usr/lib/python2.4/site-packages/diamond/util.py to util.pyc
byte-compiling /usr/lib/python2.4/site-packages/diamond/gmetric.py to gmetric.pyc
byte-compiling /usr/lib/python2.4/site-packages/diamond/error.py to error.pyc
<snip>

This is running python 2.4. Let me know if I need to gather any more information.

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
