### ISSUE TITLE
Run diamond with another python

### ISSUE THREAD

**Issue by jfroche** [BrightcoveOS/Diamond#765]
Hello,

We don't want to pollute system python with eggs specific to the diamond use case. 
So for the moment we are using virtualenv and specify the python path in the init file.
So instead of:

```
  daemon --pidfile $PIDFILE $DAEMON $DAEMON_ARGS
```

we run something link this:

```
  PYTHON=/opt/python-diamond
  daemon --pidfile $PIDFILE $PYTHON $DAEMON $DAEMON_ARGS
```

It would be nice to provide upstart/systemd ready with this usecase (fetching PYTHON from /etc/default/diamond or /etc/sysconfig/diamond).

I am ready to do a pull request if you are ok with the idea.

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
