### ISSUE TITLE
"pip install diamond" failed (CentOS 7, diamond 3.5.0)

### ISSUE THREAD

**Issue by AlexAkulov** [BrightcoveOS/Diamond#773]
Hello,
I can not install Diamond through "pip" in CentOS 7
Installation fails with the error: 

> ...
> error: can't copy 'rpm/systemd/diamond.service': doesn't exist or not a regular file
> ...

File setup.py in package diamond-3.5.0.tar.gz contains:

``` python
if distro in ['centos', 'redhat', 'debian', 'fedora']:
            data_files.append(('/etc/init.d',
                               ['bin/init.d/diamond']))
            data_files.append(('/var/log/diamond',
                               ['.keep']))
>>>            if distro_major_version >= '7' and not distro == 'debian':
                data_files.append(('/usr/lib/systemd/system',
                                   ['rpm/systemd/diamond.service']))
            elif distro_major_version >= '6' and not distro == 'debian':
                data_files.append(('/etc/init',
                                   ['rpm/upstart/diamond.conf']))
```

but there is no file "rpm/systemd/diamond.service" in the archive

**Comment by AlexAkulov** [comment]
In version 4.0.41 of the problem is present

**Comment by amitgilad3** [comment]
any update on the issue??

**Comment by mrh666** [comment]
I solve it this way:
git clone https://github.com/python-diamond/Diamond.git
cd Diamond
python setup.py build
python setup.py install
cp /etc/diamond/diamond.conf.example /etc/diamond/diamond.conf
systemctl enable diamond

AND...
# ps xa | grep diamond
65 ? Ss 0:03 /usr/bin/python /usr/bin/diamond --log-stdout --foreground

Good luck.

**Comment by AlexAkulov** [comment]
Its not the solution of the problem, it is an alternative way of intallation

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
