### ISSUE TITLE
Diamond-4.0.9 requires /usr/local/rnt/bin/python?

### ISSUE THREAD

**Issue by pythianali** [BrightcoveOS/Diamond#782]
I just built an rpm from the newest commit using python 2.6.6 on centos 6.5 and am getting the following error when trying to install it:

<pre>
Error: Package: diamond-4.0.9-0.noarch (/diamond-4.0.9-0.noarch)
           Requires: /usr/local/rnt/bin/python
</pre>

The only reference to this path I could find is here in the shebang:  https://github.com/BrightcoveOS/Diamond/blob/ea1d26f6bb2506830a2626e3e73b1e92cbac237d/src/collectors/numa/numa.py

Any ideas?

**Comment by pythianali** [comment]
I actually worked around this issue by changing the line in the shebang to 
<pre>
#!/usr/bin/pythin
</pre>

Then the rpm build worked without issue

**Comment by kormoc** [comment]
Sorry bout that. I didn't realize rpm did that.
