### ISSUE TITLE
python < 2.7 reports errors on logging.captureWarnings(True) in collector.py

### ISSUE THREAD

**Issue by audimann** [BrightcoveOS/Diamond#786]
Since we run RedHat EL 6.6 we use python 2.6.6 which should be fine according to the system requirements (python 2.4+). But we get error messages about captureWarnings not being available in line 168 in collector.py:
...
# Initialize Logger
logging.captureWarnings(True)
...

Looks like this change was introduced by
commit a2bde9d38bca99e5d71371ac22ea74ea6cae7d83
at 16th Oct. 2014

captureWarnings is only available for python 2.7+, older versions apparently don't have it

I suggest to protect this line enabling it only for python versions 2.7+, e.g.

```
    if sys.version_info > (2, 6):
        logging.captureWarnings(True)
```

Maybe somebody else knows a better solution?

Many thanks in advance
                       Michael

**Comment by kormoc** [comment]
Sorry, I had pushed f4e91e37e04ce6fe56befc0123514a6bf614a529 to my repo, but I forgot to push it upstream. I'll get that sorted out tonight

**Comment by pythianali** [comment]
I have hit this same bug as well in my latest 4.0.57-2 rpm build on CentOS 6.5 and python 2.6.6

**Comment by audimann** [comment]
Hi Rob,

 

Many thanks! Have you already pushed your change to the master?

 

Cheers

          Michael

 

Gesendet: Dienstag, 06. Januar 2015 um 03:26 Uhr
Von: "Rob Smith" <notifications@github.com>
An: BrightcoveOS/Diamond <Diamond@noreply.github.com>
Cc: audimann <audi@web.de>
Betreff: Re: [Diamond] python < 2.7 reports errors on logging.captureWarnings(True) in collector.py (#786)


Sorry, I had pushed f4e91e3 to my repo, but I forgot to push it upstream. I'll get that sorted out tonight

**Comment by KlavsKlavsen** [comment]
same issue here :(

**Comment by neoice** [comment]
this still has not been merged into master: https://github.com/BrightcoveOS/Diamond/blob/master/src/diamond/collector.py#L168

**Comment by cbrinley** [comment]
This still appears broken. Can this change please be rolled back or at least a try block put around it.

**Comment by audimann** [comment]
kormoc appears to be inactive since the beginning of January. Anybody knows how we can get the change merged into the distribution? Who to contact?

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
