### ISSUE TITLE
CPUCollector doesn't honor percore config variable for psutil collections

### ISSUE THREAD

**Issue by jamesmulcahy** [BrightcoveOS/Diamond#788]
If you don't have /proc/stat present, CPUCollector will fallback to using 'psutil' to get the CPU data.

Unfortunately, only the /proc/stat codepath checks the 'percore' config variable. 

Easy fix; will push a one shortly.

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
