### ISSUE TITLE
DiskSpaceCollector does not produce correct values.

### ISSUE THREAD

**Issue by majster-kat** [BrightcoveOS/Diamond#791]
Hi,
DiskSpaceCollector does not calculate correctly values for _avail, _free and _used space in Solaris (with zfs).
I think that the problem is in file diskspace.py, line 208. It is using data.f_bsize, but it should be using f_frsize.
See for example: https://tickets.puppetlabs.com/browse/CFACT-131 or http://www.linuxmisc.com/3-solaris/0fc0ef296e351f47.htm

Br,

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
