### ISSUE TITLE
RabbitMQCollector fails if vhost starts with /

### ISSUE THREAD

**Issue by neoice** [BrightcoveOS/Diamond#792]
I've seen numerous systems where vhosts are created starting with "/", like "/logstash". when the API calls occur, multiple slashes are condensed: /api/queues//logstash => /api/queues/logstash. this causes a 404 because no vhost "logstash" exists.

it needs to be url-encoded instead: /api/queues/%2Flogstash.

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
