### ISSUE TITLE
DiskSpaceCollector does not honour exclude_filters unless using /proc/mount

### ISSUE THREAD

**Issue by jamesmulcahy** [BrightcoveOS/Diamond#793]
This config option is ignored unless the mounts are found in /proc/mounts.  If psutil is used to determine the mounts, then no filtering occurs.

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
