### ISSUE TITLE
Stats does not work with carbon

### ISSUE THREAD

**Issue by KlavsKlavsen** [BrightcoveOS/Diamond#796]
4.0.57 (and 4.0.47 from python-diamond/diamond) starts up fine - and a tcpdump reveals they send data that looks fine.. (attached wcap file from a working server and the one running diamond-4.0.57) but it simply does not work.

I ended up installing diamond-3.5.8 - which works fine. I can't see what it does wrong.. I hope you can figure it out.

can't attach tcpdump files.. :( email me: kl at vsen.dk - and I'll email them to you.

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
