### ISSUE TITLE
publish() method in collector.py could propagate the timestamp argument

### ISSUE THREAD

**Issue by audimann** [BrightcoveOS/Diamond#799]
Hi Folks,
Right now, we can not publish timestamp data from our collector although we have the data. I propose to add the timestamp argument to the argument list of publish() and default it to None, e.g.:
change from:
def publish(self, name, value, raw_value=None, precision=0,
                metric_type='GAUGE', instance=None):
to:
def publish(self, name, value, raw_value=None, precision=0,
                metric_type='GAUGE', instance=None, timestamp=none):

and then calling Metric()
from:
# Create Metric

```
    try:
        metric = Metric(path, value, raw_value=raw_value, timestamp=None,
                        precision=precision, host=self.get_hostname(),
                        metric_type=metric_type, ttl=ttl)
```

to
# Create Metric

```
    try:
        metric = Metric(path, value, raw_value=raw_value, timestamp=timestamp,
                        precision=precision, host=self.get_hostname(),
                        metric_type=metric_type, ttl=ttl)
```

This would allow a collector to call publish() and pass the timestamp information.
Does this make sense?

Many thanks in advance
                                       Michael

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
