### ISSUE TITLE
Problem Killing Diamond Processes

### ISSUE THREAD

**Issue by bnikolaus** [BrightcoveOS/Diamond#802]
I recently migrated to a new graphite server and I am unable to kill any of my diamond processes. I am using the TCP handler and I am still seeing metrics come in on my old graphite instance, any help would be greatly appreciated.

[root@hostname ~]# /etc/init.d/diamond status
diamond dead but subsys locked

[root@hostname ~]# /etc/init.d/diamond start
Failed to acquire lockfile: /var/lock/subsys/diamond.
Held by 7224

[root@hostname ~]# ps aux | grep diamond
root      9870  1.6  1.1 190576 21524 ?        Ss   00:31   0:00 /usr/bin/python /usr/bin/diamond --foreground
root      9873  0.0  0.5 707520  9748 ?        Sl   00:31   0:00 /usr/bin/python /usr/bin/diamond --foreground
root      9894  0.0  0.8 189740 16540 ?        S    00:31   0:00 /usr/bin/python /usr/bin/diamond --foreground
root      9898  0.0  0.8 190040 16908 ?        S    00:31   0:00 /usr/bin/python /usr/bin/diamond --foreground
root      9901  0.1  0.8 190172 16992 ?        S    00:31   0:00 /usr/bin/python /usr/bin/diamond --foreground
root      9903  0.0  0.8 190172 17176 ?        S    00:31   0:00 /usr/bin/python /usr/bin/diamond --foreground
root      9923  0.0  0.8 190304 17236 ?        S    00:31   0:00 /usr/bin/python /usr/bin/diamond --foreground
root      9935  0.0  0.9 190436 17436 ?        S    00:31   0:00 /usr/bin/python /usr/bin/diamond --foreground
root      9938  0.0  0.9 190436 17400 ?        S    00:31   0:00 /usr/bin/python /usr/bin/diamond --foreground
root      9941  0.0  0.9 190568 17624 ?        S    00:31   0:00 /usr/bin/python /usr/bin/diamond --foreground
root      9944  0.0  0.9 190576 17696 ?        S    00:31   0:00 /usr/bin/python /usr/bin/diamond --foreground
root     10091  0.0  0.0 103236   856 pts/3    R+   00:31   0:00 grep diamond
root     31882  0.0  0.8 190172 17220 ?        S    Feb11   0:00 /usr/bin/python /usr/bin/diamond --foreground
root     31902  0.0  0.8 190304 17260 ?        S    Feb11   0:00 /usr/bin/python /usr/bin/diamond --foreground
root     31917  0.0  0.9 190436 17424 ?        S    Feb11   0:00 /usr/bin/python /usr/bin/diamond --foreground
root     31921  0.0  0.9 190568 17648 ?        S    Feb11   0:01 /usr/bin/python /usr/bin/diamond --foreground
root     31924  0.0  0.9 190840 18048 ?        S    Feb11   0:00 /usr/bin/python /usr/bin/diamond --foreground

**Comment by Hyperxnoia** [comment]
I face the same problem.

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
