### ISSUE TITLE
NetworkCollector's interfaces is ignored

### ISSUE THREAD

**Issue by asyd** [BrightcoveOS/Diamond#805]
Hi, 

while I have the following configuration:

```
graphite# grep interfaces /etc/diamond/collectors/NetworkCollector.conf 
interfaces = eth
```

diamond sends data for every interfaces, including tap\* and tun*, which are not in the default configuration by the way. So I suspect a bug somewhere! 

Note: greedy is enabled

**Comment by mzupan** [comment]
needs to be like

```interfaces = ["eth"]```

**Comment by asyd** [comment]
Same issue with ["eth"]

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
