### ISSUE TITLE
IPMISensorCollector has problems with missing sensors

### ISSUE THREAD

**Issue by sirtux** [BrightcoveOS/Diamond#808]
Hi,

I do see some errors like the following:

1426074797.52	[IPMISensorCollector:DEBUG]	Starting
1426074797.52	[IPMISensorCollector:DEBUG]	Interval: 300.0 seconds
1426074797.52	[IPMISensorCollector:DEBUG]	Max collection time: 270 seconds
1426074797.67	[IPMISensorCollector:ERROR]	Error when creating new Metric: path='servers.lichtspielhaus.ipmi.sensors.13-LOM', value=None
1426074797.67	[IPMISensorCollector:ERROR]	 /usr/lib/pymodules/python2.7/diamond/collector.py:396

It seems is has some problems if the values are unavailable but existing in the output of
/usr/bin/ipmitool sensor

root@lichtspielhaus:~# /usr/bin/ipmitool sensor
UID Light        | 0x0        | discrete   | 0x0180| na        | na        | na        | na        | na        | na
Health LED       | 0x0        | discrete   | 0x0180| na        | na        | na        | na        | na        | na
01-Inlet Ambient | 19.000     | degrees C  | ok    | na        | na        | na        | na        | 42.000    | 46.000
02-CPU           | 40.000     | degrees C  | ok    | na        | na        | na        | na        | 70.000    | na
03-P1 DIMM 1-2   | 28.000     | degrees C  | ok    | na        | na        | na        | na        | 87.000    | na
04-HD Max        | na         |            | na    | na        | na        | na        | na        | 60.000    | na
05-Chipset       | 54.000     | degrees C  | ok    | na        | na        | na        | na        | 105.000   | na
06-Chipset Zone  | 40.000     | degrees C  | ok    | na        | na        | na        | na        | 68.000    | 73.000
07-VR P1 Zone    | 44.000     | degrees C  | ok    | na        | na        | na        | na        | 88.000    | 93.000
08-Supercap Max  | na         |            | na    | na        | na        | na        | na        | 65.000    | na
09-iLO Zone      | 40.000     | degrees C  | ok    | na        | na        | na        | na        | 72.000    | 77.000
10-PCI 1         | na         |            | na    | na        | na        | na        | na        | 100.000   | na
11-PCI 1 Zone    | 37.000     | degrees C  | ok    | na        | na        | na        | na        | 64.000    | 69.000
12-Sys Exhaust   | 39.000     | degrees C  | ok    | na        | na        | na        | na        | 68.000    | 73.000
13-LOM           | na         |            | na    | na        | na        | na        | na        | 100.000   | na
Fan 1            | 17.640     | percent    | ok    | na        | na        | na        | na        | na        | na
Power Supply 1   | 0x0        | discrete   | 0x0180| na        | na        | na        | na        | na        | na
Memory           | 0x0        | discrete   | 0x4080| na        | na        | na        | na        | na        | na

The quick workaround was the following config in the collector config:
metrics_blacklist = '.*Max.*|.*10-PCI.*|.*13-LOM.*|.*Power.*|.*Memory.*'

Thanks,
Tom

**Comment by jaingaurav** [comment]
Hi, this issue has recently been resolved in the python-diamond/Diamond repository with PR #114. Please note to file any issues on that side as the BrightcoveOS/Diamond repository is no longer the primary repo.

**Comment by isotopp** [comment]
I wish that would be more visible on the front page of this repo.

**Comment by sirtux** [comment]
Since this is the wrong repo and I have opened a merge request on the new repo this issue is here wrong and by that closed.
