### ISSUE TITLE
ProcessResourcesCollector does not send metrics

### ISSUE THREAD

**Issue by fmargelidon** [BrightcoveOS/Diamond#811]
I recently install Diamond to send metrics to statsD. All CPU, Memory, Network... metrics works except ProcessResourcesCollector.

I don't know why but it seems ProcessResourcesCollector does not load my ProcessResourcesCollector.conf.

In file /etc/diamond/diamond.conf, I have :
collectors_config_path = /etc/diamond/collectors/

In file /etc/diamond/collectors/ProcessResourcesCollector.conf :
enabled=True
unit=kB
cpu_interval=10
[process]
[[apache2]]
name=^\/usr\/sbin\/apache2$

And when I check config status after restart Diamond service it does not appear any process or unit in kB.

diamond-setup --print -C ProcessResourcesCollector
ProcessResourcesCollector {'path_suffix': '', 'ttl_multiplier': 2, 'measure_collector_time': False, 'byte_unit': ['byte'], 'instance_prefix': 'instances', 'interval': '10', 'enabled': True, 'metrics_whitelist': None, 'metrics_blacklist': None, 'path_prefix': '', 'path': 'process', 'unit': 'B', 'hostname_method': 'smart', 'process': {}}

When I set log in DEBUG mode I have the following output :
[2015-03-26 14:46:23,884] [MainThread] Starting process Handlers
[2015-03-26 14:46:24,892] [MainThread] Starting
[2015-03-26 14:46:24,893] [MainThread] Interval: 10.0 seconds
[2015-03-26 14:46:24,893] [MainThread] Max collection time: 9 seconds
[2015-03-26 14:46:24,912] [MainThread] Collection took 18 ms
[2015-03-26 14:46:34,913] [MainThread] Collection took 9 ms
[2015-03-26 14:46:44,912] [MainThread] Collection took 7 ms
[2015-03-26 14:46:54,919] [MainThread] Collection took 15 ms
[2015-03-26 14:47:04,919] [MainThread] Collection took 15 ms

So I don't understand why I have not metrics in archive.log or in my statsD handler.

And I have a questions also to know how collect metrics for all process running on a server ? 

Thanks in advance

**Comment by dellis23** [comment]
I'm having issues with this same collector.  From what I can tell, it's unable to import `psutil`, despite it being installed on my system and able to be imported when I launch a python shell as the user diamond runs as.  I suspect this is a path issue, but I'm having issues getting visibility into what exactly is causing the issue to arise.  For a while, I was getting the following in my logs:

```
[2015-03-30 10:14:27,473] [Thread-1] Collecting data from: ProcessResourcesCollector
[2015-03-30 10:14:27,474] [Thread-1] Unable to import psutil
[2015-03-30 10:14:27,474] [Thread-1] No process resource metrics retrieved
```

For some reason, even this log output seems to have stopped.

**Comment by bnikolaus** [comment]
+1 same issue.

**Comment by zhendongli** [comment]
+1 same issue.

**Comment by jaingaurav** [comment]
What version of diamond is the reproducible on? Note that the project has move to https://github.com/python-diamond/Diamond. Please try installing the latest package from github source (as opposed to pypi) to verify is this issue still exists.

**Comment by shiplu** [comment]
How did you install `psutil` with `pip`. If you use `pip install psutil` it'll install in the current users site-packages directory.  This is same as `pip install --user psutil`. For diamond to grab this package you need to install it with `--system` switch

    pip install --system psutil

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
