### ISSUE TITLE
error when config multigraphitehandler

### ISSUE THREAD

**Issue by jindov** [BrightcoveOS/Diamond#815]
Hi guys,

I've configured diamond with multigraphitehandler, this is my config file diamond.conf:

....
[server]

handlers = diamond.handler.graphite.GraphiteHandler, diamond.handler.archive.ArchiveHandler
.....

[[MultiGraphiteHandler]]

host = graphite.example1.com, graphite.example2.com

port = 2003

timeout = 15

batch = 1

[[MultiGraphitePickleHandler]]

host = graphite.example1.com, graphite.example2.com

port = 2004

timeout = 15

batch = 256
......

but diamond.log has error:
GraphiteHandler: Failed to connect to localhost:2003. [Errno 111] Connection refused.

Anyone have idea?

**Comment by dmitriykulishenko** [comment]
you shall declare handler to use, for MultiGraphite handler, edit handlers variable to:
diamond.handler.multigraphite.MultiGraphiteHandler

**Comment by jindov** [comment]
Thank, it's worked find
