### ISSUE TITLE
run phpfpm monitor for multi site

### ISSUE THREAD

**Issue by jindov** [BrightcoveOS/Diamond#818]
Hi guys,

I've set up 3 host on nginx: example.com, page1.example.com, page2.example.com with 3 configuration corresponding in php-fpm: www, page1, page2 with:
pm.status_path = /www-status, pm.status_path = /page1-status, pm.status_path = /page2-status, It's working with curl localhost/www-status and so on but I want to know how to config diamond collectors to collect the statics of 3 host, this is my PhpFpmCollector.conf:

enabled = True
status_uri = /www-status /page1-status /page2-status

is it correct? and I have to edit in /usr/share/diamond/collectors/phpfpm/phpfpm.py?

Thank you

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
