### ISSUE TITLE
memory_docker: Doesn't work on newer kernels (e.g. RHEL7).

### ISSUE THREAD

**Issue by docwhat** [BrightcoveOS/Diamond#821]
On RHEL 7, the `MemoryDockerCollector` doesn't understand Cgroups output which looks like this:

```
diamond.example01.memory_cgroup..system.slice.docker-6bd6b9b21fd4e1163dbda14c9c8db0396c7d5ae010e6318f3214dfafe4c1aa67.scope.swap 0 1434133484
diamond.example01.memory_cgroup..system.slice.docker-6bd6b9b21fd4e1163dbda14c9c8db0396c7d5ae010e6318f3214dfafe4c1aa67.scope.total_rss 15310848 1434133484
diamond.example01.memory_cgroup..system.slice.docker-6bd6b9b21fd4e1163dbda14c9c8db0396c7d5ae010e6318f3214dfafe4c1aa67.scope.rss 15310848 1434133484
```

I suspect that `memory_cgroup` is having trouble, too.

Linux kernel: `3.10.0-229.4.2.el7.x86_64`
Diamond: 4.0.46

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
