### ISSUE TITLE
customized collector not collecting data

### ISSUE THREAD

**Issue by andrewCSE** [BrightcoveOS/Diamond#826]
diamond-setup -c /etc/diamond/diamond.conf -C XenvmCollector 
XenvmCollector {'path_suffix': '', 'splay': 1, 'measure_collector_time': False, 'interval': '60', 'byte_unit': ['byte'], 'path_prefix': 'monitor.usdev800.10_32_70_0', 'path': 'virtualmachines', 'instance_prefix': 'instances', 'enabled': True, 'method': 'Sequential', 'hostname': '10_32_70_12_1e29028d-c493-46d3-8c45-7ab4d8d9f39c'}

my OS: Linux 0-25-90-68-7a-d 3.8.13-68.2.2.2.el6uek.x86_64 #2 SMP Fri Jun 19 16:29:40 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
Diamond version 3.3.544

Another wired thing, the data is collected if I restart diamond

**Comment by andrewCSE** [comment]
When I run diamond in foreground mode, I can see my collector is loaded, is scheduled and starts collecting data.
I can also run my collector using the -r option to just run my single collector, and it works fine. However, this only allows me to run it once and exit, but I need to continuously collecting the data, and I don't want to restart diamond as the restarting interrupt the other collectors. 
Is there any way to solve this issue? or walk-around method?

Thanks a lot.

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
