### ISSUE TITLE
Need help understanding the metrics coming from NetworkCollector

### ISSUE THREAD

**Issue by lynchc** [BrightcoveOS/Diamond#831]
I'm running the docker diamond container on a host and it says it's sending the metrics rx and tx bits and bytes into graphite. I see them there but the values aren't even close to what I'm seeing live on the machine with iftop (the values from the network collector are much less and tx is higher than rx which is wrong. It's almost like it's pulling from the wrong device or something). I'm assuming i'm calculating this wrong on graphite or doing something else wrong but was wondering if anyone else had similar issues

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
