### ISSUE TITLE
Document threading

### ISSUE THREAD

**Issue by maxwax** [BrightcoveOS/Diamond#838]
I've just upgraded from Diamond 3.x to 4.x and I'm noticing that instead of a single process, it looks like we now have a multi-threaded model.

Could anyone explain this briefly, so we can identify a new normal? I'd like to know what to expect and if the number of processes/threads might vary based on handlers, collectors, etc. 

Thanks!

This is the output from # ps -eLo pid,ppid,nlwp,lwp,cmd on my RHEL 6.x system:

``` bash
PID  PPID NLWP   LWP CMD
 8971     1    1  8971 /usr/bin/python /usr/bin/diamond -p /var/run/diamond.pid
 8972  8971   10  8972 /usr/bin/python /usr/bin/diamond -p /var/run/diamond.pid
 8972  8971   10  8986 /usr/bin/python /usr/bin/diamond -p /var/run/diamond.pid
 8972  8971   10  8992 /usr/bin/python /usr/bin/diamond -p /var/run/diamond.pid
 8972  8971   10  8997 /usr/bin/python /usr/bin/diamond -p /var/run/diamond.pid
 8972  8971   10  9002 /usr/bin/python /usr/bin/diamond -p /var/run/diamond.pid
 8972  8971   10  9020 /usr/bin/python /usr/bin/diamond -p /var/run/diamond.pid
 8972  8971   10  9033 /usr/bin/python /usr/bin/diamond -p /var/run/diamond.pid
 8972  8971   10  9062 /usr/bin/python /usr/bin/diamond -p /var/run/diamond.pid
 8972  8971   10  9068 /usr/bin/python /usr/bin/diamond -p /var/run/diamond.pid
 8972  8971   10  9117 /usr/bin/python /usr/bin/diamond -p /var/run/diamond.pid
 8984  8971    1  8984 /usr/bin/python /usr/bin/diamond -p /var/run/diamond.pid
 8988  8971    1  8988 /usr/bin/python /usr/bin/diamond -p /var/run/diamond.pid
 8990  8971    1  8990 /usr/bin/python /usr/bin/diamond -p /var/run/diamond.pid
 8995  8971    1  8995 /usr/bin/python /usr/bin/diamond -p /var/run/diamond.pid
 9000  8971    1  9000 /usr/bin/python /usr/bin/diamond -p /var/run/diamond.pid
 9006  8971    1  9006 /usr/bin/python /usr/bin/diamond -p /var/run/diamond.pid
 9018  8971    1  9018 /usr/bin/python /usr/bin/diamond -p /var/run/diamond.pid
 9025  8971    1  9025 /usr/bin/python /usr/bin/diamond -p /var/run/diamond.pid
 9031  8971    1  9031 /usr/bin/python /usr/bin/diamond -p /var/run/diamond.pid
```

**Comment by jaingaurav** [comment]
In diamond 4.x we have switched to a new threading model whereby there is a thread per collector. You should observe the names of the threads to contain the collector name. This model allows users to be run collectors are different frequencies with different collect times such that a long running collector will not cause other collectors from missing their deadlines.

**Comment by jaingaurav** [comment]
And yes, documentation is needs updating. We're trying to fix up the existing documentation scripts for collectors and diamond core

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
