### ISSUE TITLE
Unable to send solrColletor data to graphite

### ISSUE THREAD

**Issue by brijesh27** [BrightcoveOS/Diamond#845]
m working on Diamond version 3.3.476.  I am trying to send data to graphite for solr. As solrcollector is not bydefautlt not present so i have created the directory 'solr' under  '/usr/share/diamond/collectors' 
and created the file solr.py  from  "https://github.com/piontas/Diamond/blob/c1fdcf3ec0b872056700d3a388674173099e7063/src/collectors/solr/solr.py "   and then created a file SolrCollector.conf under '/etc/diamond/collectors' and restarted the diamond but still m unable to send the data to graphite.

i am getting below in diamond logs : 

[2016-02-08 22:50:15,273] [Thread-1] http://localhost:8983//solr/admin/cores?action=STATUS&wt=json: HTTP Error 404: Not Found

**Comment by brijesh27** [comment]
fixed the above error , now getting : 

File "/usr/lib/python2.6/site-packages/diamond/collector.py", line 412, in _run
    self.collect()
  File "/usr/share/diamond/collectors/solr/solr.py", line 138, in collect
    standard = stats["QUERYHANDLER"]["standard"]["stats"]
KeyError: 'standard'

**Comment by Zurkdahool** [comment]
changed   in line 138 ["standard"] into ["/select"]  seems to be working for me with Solr 6.2.1

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
