### ISSUE TITLE
RedisCollector: failed to connect to localhost:6379. __init__() got an unexpected keyword argument 'unix_socket_path'.

### ISSUE THREAD

**Issue by MiteshShah** [BrightcoveOS/Diamond#846]
```
yum install python-redis
diamond-setup -C RedisCollector
```

```
echo -e "import redis\nprint redis.__version__" | python
2.0.0
```

```
cat /etc/diamond/collectors/RedisCollector.conf 
enabled = True
ttl_multiplier = 2
path_suffix = ""
measure_collector_time = True
byte_unit = byte,
db = 0
instances = localhost:6379,
host = localhost
timeout = 10
databases = 16
port = 6379
```

ISSUE - [2016-02-26 09:34:05,030] [MainThread] RedisCollector: failed to connect to localhost:6379. **init**() got an unexpected keyword argument 'unix_socket_path'.

**Comment by loweryaustin** [comment]
For the people that are finding this later on, the solution is to uninstall python-redis with yum, and then re install with pip.
```
$ yum remove python-redis
$ pip install redis
```

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
