### ISSUE TITLE
Error: I/O operation in RabbitMQ Collector

### ISSUE THREAD

**Issue by blaztoff** [BrightcoveOS/Diamond#847]
I have been trying to get this to work for quite a while. I am using the latest collector and RabbitMQ 3.6.1-1

I am getting this error in the log:

An error occurred collecting from RabbitMQ, I/O operation on closed file

Any idea what this is? The logging does not tell me much here

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
