### ISSUE TITLE
ElasticSearch collector doesn't work on ElasticSearch 2.0

### ISSUE THREAD

**Issue by stith** [BrightcoveOS/Diamond#860]
ElasticSearch's stats API seems to have changed in v2, which causes _silent_ failure of the ElasticSearch collector. I believe the only breaking change is the removal of the `network` stat, as noted [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_stats_info_and_literal_cat_literal_changes.html). If I comment out that line in the collector it seems to run fine.

**Comment by ricard0ff** [comment]
https://github.com/python-diamond/Diamond/commit/52f185ef43ad4047f66e803e8572759bf3e81f9e

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
