### ISSUE TITLE
Start in SUSE error

### ISSUE THREAD

**Issue by jacksu** [BrightcoveOS/Diamond#863]
make run
make: git: Command not found
./bin/diamond --configfile=conf/diamond.conf --foreground --log-stdout
1472807090.2    [MainProcess:INFO]  Changed UID: 0 () GID: 0 ().
1472807090.22   [MainProcess:ERROR] Unhandled exception: 'list' object has no attribute 'split'
1472807090.22   [MainProcess:ERROR] ./bin/diamond:299
1472807090.22   [MainProcess:ERROR] traceback: Traceback (most recent call last):
  File "./bin/diamond", line 291, in main
    server.run()
  File "/usr/local/lib64/python2.6/site-packages/diamond/server.py", line 96, in run
    handlers = handlers.split(',')
AttributeError: 'list' object has no attribute 'split'

**Comment by hostingwalk** [comment]
What GIT command you use or command ?

**Comment by jacksu** [comment]
must need git？

**Comment by hostingwalk** [comment]
Can you just give more information, when this error appear, or like what is the last command you run ?

**Comment by jacksu** [comment]
I use the command:make run

**Comment by kormoc** [comment]
This repo has moved to https://github.com/python-diamond/Diamond

Please open a new ticket there if this issue is not resolved with the current code there.

Thanks!
