### ISSUE TITLE
mongodb collector is not working 

### ISSUE THREAD

**Issue by brijesh27** [BrightcoveOS/Diamond#877]
Hi ,

I have started the mongodb collector , its showing below in the logs =>

Couldnt connect to mongodb: 'module' object has no attribute 'Connection'

mongodb = 3.2
pymongo = 3.0.3

please let me know how can i fix this

**Comment by r3cgm** [comment]
Hi. This project has been discontinued but has been taken over by the excellent pythond/diamond project here on github. Good chance your issue has been fixed there. Good luck.

**Comment by brijesh27** [comment]
Thanks
