### ISSUE TITLE
ProcessStatCollector must not calculate derivative of procs_running and procs_blocked

### ISSUE THREAD

**Issue by languitar** [BrightcoveOS/Diamond#881]
`procs_running` and `procs_blocked` represent the current number of processes in the respective state. Therefore, `ProcessStatCollector` must not calculate the derivative of these values to keep them interpretable.

For reference: http://man7.org/linux/man-pages/man5/proc.5.html

**Comment by r3cgm** [comment]
Hi languitar. Just a heads up this project has been mothballed and replaced by https://github.com/python-diamond

**Comment by languitar** [comment]
Yikes, sure. Just ended up at the wrong place via google...
