### ISSUE TITLE
Change project description to say about depreciation

### ISSUE THREAD

**Issue by gjedeer** [BrightcoveOS/Diamond#882]
It's not very visible that this project is unmaintained. Could you please edit the project description which is displayed on the top of the website (below "BrightcoveOS/Diamond") to point to python-diamond?

The README is okay but it's at the bottom of the page and it's not very visible.

**Comment by kormoc** [comment]
Alas, we can't :( This requires some of the permissions that we don't have, hence the move to the new url.
